INCLUDE := ../../makefile-include
include $(INCLUDE)/preamble.mk

# default rules, omit and override as needed
include $(INCLUDE)/downloads.mk
include $(INCLUDE)/meta.mk
include $(INCLUDE)/map.mk
include $(INCLUDE)/all.mk
include $(INCLUDE)/clean.mk
include $(INCLUDE)/fullclean.mk
