#!/usr/bin/env bash

workingDir="${BASH_SOURCE%/*}"
geomsDir1="$workingDir/downloads/countries-wof-default"
geomsDir2="$workingDir/downloads/countries-wof-naturalearth-alt"

# dependencies
geojsonMergeBin=geojson-merge    # https://github.com/mapbox/geojson-merge
geojsonExtentBin=geojson-extent  # https://github.com/mapbox/geojson-extent
jqBin=jq                         # https://stedolan.github.io/jq/

# https://github.com/topojson/topojson
geo2topoBin=geo2topo
topo2geoBin=topo2geo
topoquantizeBin=topoquantize
toposimplifyBin=toposimplify

# https://github.com/d3/d3-geo
# https://github.com/d3/d3-geo-projection
geo2svgBin=geo2svg
geoprojectBin=geoproject
geostitchBin=geostitch

# scaling, simplification
width=960
simplification=5
quantization=1e6
subPixelPercision=1

# TODO: probably better to read in wofids again rather than rely on dir being correct
geojson=$($geojsonMergeBin "$geomsDir1"/* "$geomsDir2"/* \
  | $geostitchBin \
  | $geoprojectBin "d3.geoNaturalEarth1().fitWidth($width, d)" \
  | $geo2topoBin - \
  | $toposimplifyBin -f -p $simplification \
  | $topoquantizeBin $quantization \
  | $topo2geoBin - )

# get our final dimens
read -d '' xmin ymin xmax ymax < <(echo "$geojson" | $geojsonExtentBin | jq '.[]')

svg=$(echo $geojson \
  | $jqBin -c '.features[]' \
  | $geo2svgBin -n -w "$xmax" -h "$ymax" -p "$subPixelPercision")

echo $svg
