#!/usr/bin/env bash

# FIXME: A space is appearing between charcaritta & villa crespo

workingDir="${BASH_SOURCE%/*}"
geomsDir="$workingDir/downloads/geoms"

# dependencies
geojsonMergeBin=geojson-merge    # https://github.com/mapbox/geojson-merge
geojsonExtentBin=geojson-extent  # https://github.com/mapbox/geojson-extent
jqBin=jq                         # https://stedolan.github.io/jq/

# https://github.com/topojson/topojson
geo2topoBin=geo2topo
topo2geoBin=topo2geo
topoquantizeBin=topoquantize
toposimplifyBin=toposimplify

# https://github.com/d3/d3-geo
# https://github.com/d3/d3-geo-projection
geo2svgBin=geo2svg
geoprojectBin=geoproject

# scaling, simplification
pixels=960
simplification=1
quantization=1000
subPixelPercision=0

# TODO: probably better to read in wofids again rather than rely on dir being correct
geojson=$($geojsonMergeBin "$geomsDir"/* | $geoprojectBin "d3.geoAzimuthalEqualArea().rotate([58.5033, 34.6156])")

# move top left to [0, 0], scale it appropriately
read xmin ymin xmax ymax < <(echo "$geojson" | $geojsonExtentBin | tr '[,]', ' ')
geojson=$(echo $geojson \
          | $geoprojectBin "d3.geoIdentity().translate([-$xmin, -$ymin])" \
          | $geoprojectBin "d3.geoIdentity().scale($pixels/Math.max($xmax-$xmin, $ymax-$ymin))")

# get our final dimens
read xmin ymin xmax ymax < <(echo "$geojson" | $geojsonExtentBin | tr '[,]', ' ')

topojson=$(echo $geojson \
           | $geo2topoBin - \
           | $toposimplifyBin -f -p $simplification \
           | $topoquantizeBin $quantization)
svg=$(echo $topojson \
      | $topo2geoBin - \
      | $jqBin -c '.features[]' \
      | $geo2svgBin -n -w "$xmax" -h "$ymax" -p "$subPixelPercision")

echo $svg
