#!/usr/bin/env bash

workingDir="${BASH_SOURCE%/*}"
binDir="${workingDir}/../../bin"
defaultGeomsDir="$workingDir/default-geoms"

# https://www.gnu.org/software/parallel/
parallelBin=parallel

wofDownloadBin="${binDir}/wof-download"
downloadConcurrency=6 # copying chrome, max connections per hostname

wofIds=$(cat "$workingDir/wofIds" |  sed -e 's/#.*$//' -e '/^$/d')
mkdir -p "$defaultGeomsDir"
$parallelBin -j "$downloadConcurrency" "$wofDownloadBin" -o "$defaultGeomsDir" ::: $wofIds
