#!/usr/bin/env bash

workingDir="${BASH_SOURCE%/*}"
defaultGeomsDir="$workingDir/default-geoms"

title="States of the USA"
titleSlug='states-of-the-usa'
description="The 50 states, and the District of Columbia, of the United States of America."
license="Data from Who's On First. <a href="http://whosonfirst.mapzen.com#License">License</a>"
outputMetaFilename="$titleSlug.meta.json"

# https://stedolan.github.io/jq/
jqBin=jq


metaJson=$($jqBin -n "{title: \"$title\", titleSlug: \"$titleSlug\", description: \"$description\",
                       license: \"$license\", objects: {}}")
for wofPath in "$defaultGeomsDir"/*; do
  wofId=$(jq '.id' "$wofPath")
  wofNameQuoted=$(jq '.properties."wof:name"' "$wofPath")
  metaJson=$(echo $metaJson | $jqBin ".objects += {\"$wofId\": $wofNameQuoted}")
done

echo $metaJson | $jqBin -c . > "$outputMetaFilename"
