#!/usr/bin/env bash

workingDir="${BASH_SOURCE%/*}"
altGeomsDir="$workingDir/downloads/wof-alt-geoms"

# dependencies
geojsonMergeBin=geojson-merge    # https://github.com/mapbox/geojson-merge
geojsonExtentBin=geojson-extent  # https://github.com/mapbox/geojson-extent
jqBin=jq                         # https://stedolan.github.io/jq/

# https://github.com/topojson/topojson
geo2topoBin=geo2topo
topo2geoBin=topo2geo
topoquantizeBin=topoquantize
toposimplifyBin=toposimplify

# https://github.com/d3/d3-geo
# https://github.com/d3/d3-geo-projection
geo2svgBin=geo2svg
geoprojectBin=geoproject
geostitchBin=geostitch

# scaling, simplification
width=960
simplification=1
quantization=10000
subPixelPercision=0

# TODO: probably better to read in wofids again rather than rely on dir being correct
geojson=$($geojsonMergeBin "$altGeomsDir"/* \
  | $geostitchBin \
  | $geoprojectBin "d3.geoAlbersUsa().fitWidth($width, d)")

# get our final dimens
read -d '' xmin ymin xmax ymax < <(echo "$geojson" | $geojsonExtentBin | jq '.[]')

topojson=$(echo $geojson \
  | $geo2topoBin - \
  | $toposimplifyBin -f -p $simplification \
  | $topoquantizeBin $quantization)
svg=$(echo $topojson \
  | $topo2geoBin - \
  | $jqBin -c '.features[]' \
  | $geo2svgBin -n -w "$xmax" -h "$ymax" -p "$subPixelPercision")

echo $svg
